### ISSUE TITLE
Still stuck due to less knowledge in the arguments and full flow

### ISSUE THREAD

**Issue by om12nayak** [HackathonXplore15Sep/BigdataVisualization_hackthon_6thOct#2]
First of all thanks sir for replying to the issue.
Sir first thing when I tried to run the WCDriver program by making another project and adding the jar files.
- The first error that came was when I added the jar files it showed that the path library is present in both hdfs-client, common jar files, so it is throwing error there.(Refer image-1)
![image](https://user-images.githubusercontent.com/35339580/94985320-43b14100-0573-11eb-89ad-ece103e29a77.png)

- I tried to resolve it by removing the hdfs-client jar, there was no error furthermore. Then I tried to export the folder into jar file, there I got some warnings, I think this warnings you need to see. May be I am missing something.
![image](https://user-images.githubusercontent.com/35339580/94985363-a276ba80-0573-11eb-861d-077cacba4d0e.png)

- Then when I transferred the jar file to the vm and tried to run with the given command, it said that there was no WC present. I used  ` yarn jar WordsCount12.jar WC webin/ out/ -Dlog4j.configuration=log4j.properties -D mapred.map.tasks = 1`

- My doubts where I am not clear:-
  - Not knowing the arguments in the command that I am executing like the "webin/" folder should be inside the jar or it should outside the jar, same for the "out/".
  - What do we mean by on "WC" after the file name is written in the command.
  - What is the meaning of " -Dlog4j.configuration=log4j.properties"
  - Still I am not able to create a jar without the warnings, I am not sure whether I am doing the correct way or not.
  - It would be really helpful if you can give some screenshots or a video where it is clear of the full process starting from eclipse setup to running the jar file.

**Comment by HackathonXplore15Sep** [comment]
Hadoop_installation&Execution_AzureCloud_V3.0.docx check this doc. Also warning in jar creation is fine.
Check the deployment section in the document. Good going. Are u using docker or cloudera quickstart VM

**Comment by HackathonXplore15Sep** [comment]
https://edureka.wistia.com/medias/tvzfrv6bvh

**Comment by om12nayak** [comment]
> Hadoop_installation&Execution_AzureCloud_V3.0.docx check this doc. Also warning in jar creation is fine.
> Check the deployment section in the document. Good going. Are u using docker or cloudera quickstart VM

Thanks sir, I am using Cloudera quickstart VM. Let me check if I can successfully run one app.
